/* Демо-данные прототипа: инциденты, устройства, группы, сценарии, люди, эмуляция коллег.
   Их читает только встроенный сервер (server.js) — интерфейс получает данные запросами API.
   В продукте это хранилище бэкенда и внешние справочники. */
(() => {
  const ME = "Иванов А. С.";

  const SCENARIOS = {
    fire: {
      title: "Пожарная тревога",
      steps: [
        { id: "visual", type: "checkbox", label: "Тревога подтверждена по видео", required: true },
        {
          id: "verdict",
          type: "radio",
          label: "Классификация",
          required: true,
          options: ["Реальная", "Ложная", "Требует выезда"],
        },
        {
          id: "kind",
          type: "combo",
          label: "Тип сработки",
          options: ["Задымление", "Открытое пламя", "Датчик без визуального подтверждения", "Тест системы"],
        },
        { id: "note", type: "edit", label: "Комментарий / номер наряда", placeholder: "Что сделано, кого вызвали" },
        {
          id: "macros",
          type: "macros",
          label: "Макросы площадки",
          buttons: ["Оповещение по площадке", "Разблокировать эвакуационные выходы"],
        },
      ],
    },
    intrusion: {
      title: "Проникновение",
      steps: [
        { id: "visual", type: "checkbox", label: "Нарушитель виден в кадре", required: true },
        {
          id: "verdict",
          type: "radio",
          label: "Классификация",
          required: true,
          options: ["Реальное проникновение", "Персонал / ложная", "Недостаточно данных"],
        },
        {
          id: "zone",
          type: "combo",
          label: "Зона",
          options: ["Периметр", "Служебный вход", "Склад", "Офисная зона"],
        },
        { id: "note", type: "edit", label: "Описание", placeholder: "Маршрут, приметы, действия охраны" },
        { id: "macros", type: "macros", label: "Макросы", buttons: ["Включить сирену", "Переключить PTZ на зону"] },
      ],
    },
    sabotage: {
      title: "Саботаж камеры",
      steps: [
        { id: "lost", type: "checkbox", label: "Подтверждена потеря видео / закрытие объектива" },
        {
          id: "verdict",
          type: "radio",
          label: "Причина",
          required: true,
          options: ["Умышленное воздействие", "Неисправность", "Погодные условия"],
        },
        { id: "note", type: "edit", label: "Комментарий", placeholder: "Камера, симптомы, заявка в сервис" },
        { id: "macros", type: "macros", label: "Макросы", buttons: ["Создать заявку на ремонт"] },
      ],
    },
    loiter: {
      title: "Скопление / праздношатание",
      steps: [
        { id: "visual", type: "checkbox", label: "Ситуация подтверждена", required: true },
        {
          id: "verdict",
          type: "radio",
          label: "Решение",
          required: true,
          options: ["Направить охрану", "Наблюдать", "Ложная"],
        },
        { id: "note", type: "edit", label: "Комментарий" },
      ],
    },
    ppe: {
      title: "Отсутствие СИЗ",
      steps: [
        { id: "visual", type: "checkbox", label: "Отсутствие каски подтверждено по видео", required: true },
        {
          id: "verdict",
          type: "radio",
          label: "Классификация",
          required: true,
          options: ["Реальное нарушение", "Ошибка детектора", "Сотрудник вне рабочей зоны"],
        },
        {
          id: "who",
          type: "combo",
          label: "Кто нарушитель",
          options: ["Сотрудник склада", "Водитель поставщика", "Подрядчик", "Не идентифицирован"],
        },
        {
          id: "note",
          type: "edit",
          label: "Комментарий / кому передано",
          placeholder: "Табельный номер, бригадир, номер акта",
        },
        {
          id: "macros",
          type: "macros",
          label: "Макросы зоны",
          buttons: ["Голосовое оповещение в зону", "Уведомить инженера по охране труда"],
        },
      ],
    },
    alcohol: {
      title: "Превышение уровня алкоголя",
      steps: [
        { id: "visual", type: "checkbox", label: "Личность на точке прохода подтверждена по видео", required: true },
        {
          id: "verdict",
          type: "radio",
          label: "Результат проверки",
          required: true,
          options: ["Превышение подтверждено", "Повторный тест в норме", "Сбой алкорамки"],
        },
        {
          id: "level",
          type: "combo",
          label: "Показание прибора",
          options: ["0,3–0,5 ‰", "0,5–1,0 ‰", "Более 1,0 ‰", "Показание не считано"],
        },
        { id: "note", type: "edit", label: "Комментарий", placeholder: "ФИО, смена, кому передан сотрудник" },
        {
          id: "macros",
          type: "macros",
          label: "Макросы точки прохода",
          buttons: ["Заблокировать турникет", "Вызвать медпункт"],
        },
      ],
    },
    glass: {
      title: "Звук разбития стекла",
      steps: [
        { id: "audio", type: "checkbox", label: "Звуковое событие прослушано оператором", required: true },
        { id: "visual", type: "checkbox", label: "Повреждение видно на камерах зоны" },
        {
          id: "verdict",
          type: "radio",
          label: "Классификация",
          required: true,
          options: ["Разбитие витрины или стекла", "Бытовой шум: посуда, погрузка", "Ложная сработка детектора"],
        },
        { id: "note", type: "edit", label: "Комментарий", placeholder: "Что повреждено, вызвана ли охрана" },
        {
          id: "macros",
          type: "macros",
          label: "Макросы зоны",
          buttons: ["Включить сирену зоны", "Направить охрану к витрине"],
        },
      ],
    },
  };

  const DEVICE_TYPES = {
    camera: { icon: "videocam", label: "Камера видеонаблюдения" },
    "fire-detector": { icon: "local_fire_department", label: "Пожарный извещатель" },
    "panic-button": { icon: "crisis_alert", label: "Тревожная кнопка" },
    "ppe-detector": { icon: "engineering", label: "Детектор СИЗ" },
    "access-point": { icon: "sensor_door", label: "Виртуальная точка прохода" },
    microphone: { icon: "mic", label: "Микрофон" },
  };

  const DEVICE_CATALOG = {
    "device-1": { name: "Главный вход", type: "camera" },
    "device-2": { name: "Стойка ресепшн", type: "camera" },
    "device-3": { name: "Конференц-зал — сцена", type: "camera" },
    "device-4": { name: "Конференц-зал — общий план", type: "camera" },
    "device-5": { name: "Опенспейс разработки", type: "camera" },
    "device-6": { name: "Маркетинг — рабочая зона", type: "camera" },
    "device-7": { name: "Переговорная «Невада»", type: "camera" },
    "device-8": { name: "Ворота погрузки А", type: "camera" },
    "device-9": { name: "Стеллажи А1–А8", type: "camera" },
    "device-10": { name: "Зона приёмки товара", type: "camera" },
    "device-11": { name: "Разгрузочная рампа", type: "camera" },
    "device-12": { name: "Центральный проход", type: "camera" },
    "device-13": { name: "Холодильная камера", type: "camera" },
    "device-14": { name: "Пост погрузчика", type: "camera" },
    "device-15": { name: "Испытательный стенд", type: "camera" },
    "device-16": { name: "Вход в чистую зону", type: "camera" },
    "device-17": { name: "Лабораторные столы", type: "camera" },
    "device-18": { name: "Серверная стойка", type: "camera" },
    "device-19": { name: "Вытяжной шкаф", type: "camera" },
    "device-20": { name: "Коридор корпуса Б", type: "camera" },
    "device-21": { name: "Переговорная «Юпитер»", type: "camera" },
    "device-22": { name: "Офисная кухня", type: "camera" },
    "device-23": { name: "Торговый зал", type: "camera" },
    "device-24": { name: "Кассовая зона", type: "camera" },
    "device-25": { name: "Коридор примерочных", type: "camera" },
    "device-26": { name: "Витрина у входа", type: "camera" },
    "device-27": { name: "Зал ресторана", type: "camera" },
    "device-28": { name: "Кухня ресторана", type: "camera" },
    "device-29": { name: "Фойе и бар", type: "camera" },
    "device-30": { name: "Кинозал №3", type: "camera" },
    "device-31": { name: "Зона ожидания — общий план", type: "camera" },
    "device-32": { name: "Гардероб", type: "camera" },
    "device-33": { name: "Обзор поста охраны", type: "camera" },
    "device-34": { name: "КПП — проходная", type: "camera" },
    "device-35": { name: "КПП — шлагбаум и въезд", type: "camera" },
    "fire-1": { name: "Датчик дыма 1", type: "fire-detector" },
    "fire-2": { name: "Датчик дыма 2", type: "fire-detector" },
    "fire-3": { name: "Датчик дыма 3", type: "fire-detector" },
    "fire-4": { name: "Датчик дыма 4", type: "fire-detector" },
    "fire-5": { name: "Датчик дыма 5", type: "fire-detector" },
    "fire-6": { name: "Датчик дыма — зона ожидания", type: "fire-detector" },
    "panic-1": { name: "Тревожная кнопка — пост охраны", type: "panic-button" },
    "panic-2": { name: "Тревожная кнопка — ресепшн", type: "panic-button" },
    "ppe-1": { name: "Детектор СИЗ — разгрузочная рампа", type: "ppe-detector" },
    "ppe-2": { name: "Детектор СИЗ — вход в цех", type: "ppe-detector" },
    "gate-1": { name: "Точка прохода — КПП склада", type: "access-point" },
    "gate-2": { name: "Точка прохода — турникет офиса", type: "access-point" },
    "mic-1": { name: "Микрофон — витрина у входа", type: "microphone" },
    "mic-2": { name: "Микрофон — торговый зал", type: "microphone" },
  };

  const DEVICES_IN_REPAIR = ["device-9", "device-19", "device-25", "fire-3", "ppe-2"];

  const PAGE_SIZE = 8;

  function devicesOfType(type) {
    return Object.keys(DEVICE_CATALOG).filter((id) => DEVICE_CATALOG[id].type === type);
  }
  function workingOfType(type) {
    return devicesOfType(type).filter((id) => !DEVICES_IN_REPAIR.includes(id));
  }
  function inRepairOfType(type) {
    return devicesOfType(type).filter((id) => DEVICES_IN_REPAIR.includes(id));
  }

  const TOPOLOGY = [
    {
      id: "group-1",
      name: "Главный офис",
      children: [
        {
          id: "group-2",
          name: "1-й этаж",
          children: [
            {
              id: "group-3",
              name: "Приемная",
              devices: ["device-1", "device-2", "fire-1", "gate-2"],
              children: [
                { id: "group-28", name: "Зона ожидания", devices: ["device-31", "device-32", "fire-6"] },
                { id: "group-29", name: "Пост охраны", devices: ["device-33", "panic-1", "panic-2"] },
              ],
            },
            { id: "group-4", name: "Конференц-зал", devices: ["device-3", "device-4", "fire-2", "device-1"] },
          ],
        },
        {
          id: "group-5",
          name: "2-й этаж",
          children: [
            { id: "group-6", name: "Отдел разработки", devices: ["device-5"] },
            { id: "group-7", name: "Отдел маркетинга", devices: ["device-6", "device-7"] },
          ],
        },
      ],
    },
    {
      id: "group-8",
      name: "Складской комплекс",
      children: [
        {
          id: "group-9",
          name: "Этаж А",
          children: [
            { id: "group-10", name: "Склад №1", devices: ["device-8", "device-9", "device-10", "fire-3"] },
            {
              id: "group-11",
              name: "Склад №2",
              devices: ["device-11", "device-12", "device-8", "ppe-1", "ppe-2"],
            },
          ],
        },
        {
          id: "group-12",
          name: "Этаж Б",
          children: [{ id: "group-13", name: "Склад №3", devices: ["device-13", "device-14"] }],
        },
        {
          id: "group-30",
          name: "КПП и проходная",
          devices: ["device-34", "device-35", "gate-1"],
        },
      ],
    },
    {
      id: "group-14",
      name: "Технопарк",
      children: [
        {
          id: "group-15",
          name: "Корпус А",
          children: [
            { id: "group-16", name: "Лаборатория 1", devices: ["device-15", "device-16", "fire-4"] },
            { id: "group-17", name: "Лаборатория 2", devices: ["device-17", "device-18", "device-19"] },
          ],
        },
        {
          id: "group-18",
          name: "Корпус Б",
          children: [
            { id: "group-19", name: "Офис 1", devices: ["device-20", "device-15"] },
            { id: "group-20", name: "Офис 2", devices: ["device-21", "device-22"] },
          ],
        },
      ],
    },
    {
      id: "group-21",
      name: "Торговый центр",
      children: [
        {
          id: "group-22",
          name: "1-й этаж",
          children: [
            { id: "group-23", name: "Магазин 1", devices: ["device-23", "device-24", "fire-5", "mic-2"] },
            { id: "group-24", name: "Магазин 2", devices: ["device-25", "device-26", "mic-1"] },
          ],
        },
        {
          id: "group-25",
          name: "2-й этаж",
          children: [
            { id: "group-26", name: "Ресторан", devices: ["device-27", "device-28"] },
            { id: "group-27", name: "Кинотеатр", devices: ["device-29", "device-30"] },
          ],
        },
      ],
    },
    {
      id: "group-all-cameras",
      name: "Все камеры",
      description: "Сквозная подборка камер видеонаблюдения со всех площадок, разделённая по состоянию оборудования.",
      children: [
        {
          id: "group-cameras-working",
          name: "Рабочие",
          description: "Камеры в штатной работе.",
          devices: workingOfType("camera"),
        },
        {
          id: "group-cameras-repair",
          name: "В ремонте",
          description: "Камеры, временно выведенные из эксплуатации.",
          devices: inRepairOfType("camera"),
        },
      ],
    },
    {
      id: "group-fire-detectors",
      name: "Пожарные датчики",
      description: "Сквозная подборка пожарных датчиков со всех площадок, разделённая по состоянию оборудования.",
      children: [
        {
          id: "group-fire-working",
          name: "Рабочие",
          description: "Датчики в штатной работе.",
          devices: workingOfType("fire-detector"),
        },
        {
          id: "group-fire-repair",
          name: "В ремонте",
          description: "Датчики, временно выведенные из эксплуатации.",
          devices: inRepairOfType("fire-detector"),
        },
      ],
    },
    {
      id: "group-detectors",
      name: "Детекторы и микрофоны",
      description: "Сквозная подборка аналитических детекторов, точек прохода и микрофонов.",
      children: [
        {
          id: "group-ppe",
          name: "Детекторы СИЗ",
          description: "Контроль средств индивидуальной защиты в производственных зонах.",
          devices: devicesOfType("ppe-detector"),
        },
        {
          id: "group-access",
          name: "Виртуальные точки прохода",
          description: "Турникеты, КПП и алкорамки, объединённые в виртуальные точки прохода.",
          devices: devicesOfType("access-point"),
        },
        {
          id: "group-mics",
          name: "Микрофоны",
          description: "Аудиодетекция: разбитие стекла, крик, выстрел.",
          devices: devicesOfType("microphone"),
        },
      ],
    },
  ];

  function buildTree(nodes) {
    return nodes.map((node) => {
      const group = { id: node.id, name: node.name };
      if (node.description) group.description = node.description;
      group.children = node.children ? buildTree(node.children) : [];
      (node.devices || []).forEach((deviceId) => {
        group.children.push({ id: deviceId, isDevice: true });
      });
      return group;
    });
  }

  const TREE = buildTree(TOPOLOGY);

  const EVENTS = [
    {
      id: "INC-1847",
      time: "14:31:08",
      typeId: "fire",
      type: "Пожарная тревога",
      site: "Торговый центр",
      siteType: "Торговый центр",
      location: "Магазин 1, торговый зал",
      region: "Торговый центр",
      priority: "critical",
      status: "new",
      operator: null,
      slaSec: 240,
      deviceIds: ["fire-5", "device-23", "device-24"],
      media: "both",
      cameras: ["device-23", "device-24", "device-26"],
      answers: {},
      launched: [],
      log: [{ t: "14:31:08", who: "Диспетчер", text: "Событие поставлено в очередь" }],
    },
    {
      // Парный к INC-1847 однотипный инцидент: на нём проверяется «Обработать как одно» (§11)
      id: "INC-1851",
      time: "14:30:51",
      typeId: "fire",
      type: "Пожарная тревога",
      site: "Торговый центр",
      siteType: "Торговый центр",
      location: "Магазин 2, коридор примерочных",
      region: "Торговый центр",
      priority: "critical",
      status: "new",
      operator: null,
      slaSec: 240,
      deviceIds: ["fire-5", "device-26"],
      media: "both",
      cameras: ["device-26", "device-23"],
      answers: {},
      launched: [],
      log: [{ t: "14:30:51", who: "Диспетчер", text: "Событие поставлено в очередь" }],
    },
    {
      id: "INC-1850",
      time: "14:30:12",
      typeId: "glass",
      type: "Детекция звука разбития стекла",
      site: "Торговый центр",
      siteType: "Торговый центр",
      location: "Магазин 2, витрина у входа",
      region: "Торговый центр",
      priority: "high",
      status: "new",
      operator: null,
      slaSec: 300,
      deviceIds: ["mic-1", "device-26", "device-23"],
      media: "both",
      cameras: ["device-26", "device-23"],
      answers: {},
      launched: [],
      log: [
        { t: "14:30:12", who: "Аудиодетекция", text: "Микрофон «Витрина у входа»: спектр разбития стекла, 87 дБ" },
      ],
    },
    {
      id: "INC-1849",
      time: "14:29:35",
      typeId: "alcohol",
      type: "Детекция превышения уровня алкоголя",
      site: "Складской комплекс",
      siteType: "КПП",
      location: "КПП, проходная — турникет №2",
      region: "Складской комплекс",
      priority: "high",
      status: "new",
      operator: null,
      slaSec: 420,
      deviceIds: ["gate-1", "device-34", "device-35"],
      media: "both",
      cameras: ["device-34", "device-35"],
      answers: {},
      launched: [],
      log: [
        { t: "14:29:35", who: "Точка прохода", text: "Алкорамка на турникете №2: показание выше порога, проход заблокирован" },
      ],
    },
    {
      id: "INC-1846",
      time: "14:28:41",
      typeId: "intrusion",
      type: "Проникновение",
      site: "Складской комплекс",
      siteType: "Склад",
      location: "Склад №1, ворота погрузки А",
      region: "Складской комплекс",
      priority: "high",
      status: "foreign",
      operator: "Петрова М.",
      slaSec: 420,
      deviceIds: ["device-8", "device-9", "device-10"],
      media: "video",
      cameras: ["device-8", "device-10", "device-11"],
      answers: { visual: true, verdict: "Недостаточно данных" },
      launched: [],
      log: [
        { t: "14:28:41", who: "Диспетчер", text: "Событие поставлено в очередь" },
        { t: "14:29:02", who: "Петрова М.", text: "Взято в работу · шаг 2/5" },
      ],
    },
    {
      id: "INC-1848",
      time: "14:26:14",
      typeId: "ppe",
      type: "Отсутствие каски",
      site: "Складской комплекс",
      siteType: "Склад",
      location: "Склад №2, разгрузочная рампа",
      region: "Складской комплекс",
      priority: "medium",
      status: "foreign",
      operator: "Сидоров К.",
      stepIndex: 2,
      slaSec: 720,
      deviceIds: ["ppe-1", "device-11", "device-8"],
      media: "both",
      cameras: ["device-11", "device-8"],
      answers: { visual: true, verdict: "Реальное нарушение" },
      launched: [],
      log: [
        { t: "14:26:14", who: "Детектор СИЗ", text: "Зона рампы: человек без защитной каски, достоверность 0,93" },
        { t: "14:26:58", who: "Сидоров К.", text: "Взято в работу" },
        { t: "14:27:40", who: "Сидоров К.", text: "Нарушение подтверждено, ищу табельный номер" },
      ],
    },
    {
      id: "INC-1845",
      time: "14:22:17",
      typeId: "sabotage",
      type: "Саботаж камеры",
      site: "Торговый центр",
      siteType: "Торговый центр",
      location: "Магазин 2, коридор примерочных",
      region: "Торговый центр",
      priority: "medium",
      status: "mine",
      operator: "Иванов А. С.",
      paused: true,
      stepIndex: 1,
      slaSec: 900,
      deviceIds: ["device-25"],
      media: "video",
      cameras: ["device-25", "device-26"],
      answers: { lost: true },
      launched: [],
      log: [
        { t: "14:22:17", who: "Диспетчер", text: "Потеря видеопотока «Коридор примерочных»" },
        { t: "14:23:05", who: "Иванов А. С.", text: "Взято в работу" },
        { t: "14:24:40", who: "Иванов А. С.", text: "Обработка приостановлена на шаге 2" },
      ],
    },
    {
      id: "INC-1844",
      time: "14:19:03",
      typeId: "loiter",
      type: "Скопление людей",
      site: "Торговый центр",
      siteType: "Торговый центр",
      location: "1-й этаж, витрина у входа",
      region: "Торговый центр",
      priority: "medium",
      status: "foreign",
      operator: "Гусев Р. А.",
      stepIndex: 1,
      slaSec: 600,
      deviceIds: ["device-26", "device-23"],
      media: "both",
      cameras: ["device-26", "device-23"],
      answers: { visual: true },
      launched: [],
      log: [
        { t: "14:19:03", who: "Диспетчер", text: "Детектор скопления" },
        { t: "14:19:48", who: "Гусев Р. А.", text: "Взято в работу · смотрю по камерам входной группы" },
      ],
    },
    {
      id: "INC-1843",
      time: "14:11:55",
      typeId: "intrusion",
      type: "Проникновение",
      site: "Главный офис",
      siteType: "Офис",
      location: "Приемная, пост охраны",
      region: "Главный офис",
      priority: "high",
      status: "escalated",
      operator: "Дежурный ЦОД",
      slaSec: 180,
      deviceIds: ["panic-1", "device-33"],
      media: "map",
      cameras: [],
      answers: { visual: true, verdict: "Реальное проникновение" },
      launched: ["Включить сирену"],
      log: [
        { t: "14:12:20", who: "Сидоров К.", text: "Эскалация в ЦОД: нет доступа к площадке" },
      ],
    },
    {
      id: "INC-1842",
      time: "14:06:12",
      typeId: "fire",
      type: "Пожарная тревога",
      site: "Складской комплекс",
      siteType: "Склад",
      location: "Склад №1, датчик дыма 3",
      region: "Складской комплекс",
      priority: "high",
      status: "new",
      operator: null,
      slaSec: 300,
      deviceIds: ["fire-3", "device-8", "device-10"],
      media: "map",
      cameras: [],
      answers: {},
      launched: [],
      log: [{ t: "14:06:12", who: "Диспетчер", text: "Сработка пожарного датчика" }],
    },
    {
      id: "INC-1841",
      time: "13:58:44",
      typeId: "loiter",
      type: "Скопление людей",
      site: "Торговый центр",
      siteType: "Торговый центр",
      location: "2-й этаж, фойе кинотеатра",
      region: "Торговый центр",
      priority: "medium",
      status: "new",
      operator: null,
      slaSec: 660,
      deviceIds: ["device-29", "device-30"],
      media: "video",
      cameras: ["device-29", "device-30"],
      answers: {},
      launched: [],
      log: [{ t: "13:58:44", who: "Видеоаналитика", text: "Превышение плотности людей в зоне" }],
    },
    {
      id: "INC-1840",
      time: "13:51:09",
      typeId: "sabotage",
      type: "Саботаж камеры",
      site: "Технопарк",
      siteType: "Лаборатория",
      location: "Корпус А, лаборатория 2",
      region: "Технопарк",
      priority: "medium",
      status: "foreign",
      operator: "Сидоров К.",
      slaSec: 540,
      deviceIds: ["device-18", "device-17"],
      media: "video",
      cameras: ["device-18"],
      answers: { lost: true },
      launched: [],
      log: [
        { t: "13:51:09", who: "Видеоаналитика", text: "Потеря видеопотока" },
        { t: "13:52:31", who: "Сидоров К.", text: "Взято в работу · шаг 1/4" },
      ],
    },
    {
      id: "INC-1839",
      time: "13:44:57",
      typeId: "intrusion",
      type: "Проникновение",
      site: "Складской комплекс",
      siteType: "Склад",
      location: "Склад №2, центральный проход",
      region: "Складской комплекс",
      priority: "high",
      status: "new",
      operator: null,
      slaSec: 360,
      deviceIds: ["device-11", "device-12"],
      media: "both",
      cameras: ["device-11"],
      answers: {},
      launched: [],
      log: [{ t: "13:44:57", who: "Диспетчер", text: "Событие поставлено в очередь" }],
    },
    {
      id: "INC-1838",
      time: "13:37:12",
      typeId: "fire",
      type: "Пожарная тревога",
      site: "Главный офис",
      siteType: "Офис",
      location: "1-й этаж, конференц-зал",
      region: "Главный офис",
      priority: "critical",
      status: "new",
      operator: null,
      slaSec: 210,
      deviceIds: ["fire-2", "device-3", "device-4"],
      media: "both",
      cameras: ["device-3", "device-4"],
      answers: {},
      launched: [],
      log: [{ t: "13:37:12", who: "Диспетчер", text: "Сработка пожарного датчика" }],
    },
    {
      id: "INC-1837",
      time: "13:29:38",
      typeId: "loiter",
      type: "Скопление людей",
      site: "Главный офис",
      siteType: "Офис",
      location: "Приемная, зона ожидания",
      region: "Главный офис",
      priority: "low",
      status: "closed",
      operator: "Иванов А. С.",
      slaSec: 0,
      deviceIds: ["device-31", "device-32"],
      media: "video",
      cameras: ["device-31"],
      answers: { visual: true, verdict: "Наблюдать", note: "Очередь на регистрацию, разошлись сами" },
      launched: [],
      log: [
        { t: "13:29:38", who: "Видеоаналитика", text: "Скопление в зоне ожидания" },
        { t: "13:35:02", who: "Иванов А. С.", text: "Инцидент закрыт" },
      ],
    },
    {
      id: "INC-1836",
      time: "13:22:05",
      typeId: "intrusion",
      type: "Проникновение",
      site: "Технопарк",
      siteType: "Лаборатория",
      location: "Корпус А, вход в чистую зону",
      region: "Технопарк",
      priority: "high",
      status: "escalated",
      operator: "Дежурный ЦОД",
      slaSec: 150,
      deviceIds: ["device-16", "device-15"],
      media: "both",
      cameras: ["device-16"],
      answers: { visual: true, verdict: "Недостаточно данных" },
      launched: [],
      log: [{ t: "13:24:11", who: "Петрова М.", text: "Эскалация: требуется допуск в чистую зону" }],
    },
    {
      id: "INC-1835",
      time: "13:14:49",
      typeId: "sabotage",
      type: "Саботаж камеры",
      site: "Складской комплекс",
      siteType: "Склад",
      location: "Склад №3, холодильная камера",
      region: "Складской комплекс",
      priority: "medium",
      status: "new",
      operator: null,
      slaSec: 480,
      deviceIds: ["device-13"],
      media: "video",
      cameras: ["device-13"],
      answers: {},
      launched: [],
      log: [{ t: "13:14:49", who: "Видеоаналитика", text: "Резкое падение освещённости кадра" }],
    },
    {
      id: "INC-1834",
      time: "13:06:31",
      typeId: "fire",
      type: "Пожарная тревога",
      site: "Торговый центр",
      siteType: "Торговый центр",
      location: "2-й этаж, кухня ресторана",
      region: "Торговый центр",
      priority: "critical",
      status: "mine",
      operator: "Иванов А. С.",
      paused: true,
      stepIndex: 2,
      slaSec: 195,
      deviceIds: ["device-28", "device-27"],
      media: "both",
      cameras: ["device-27", "device-28"],
      answers: { visual: true, verdict: "Реальная", kind: "Задымление" },
      launched: [],
      log: [
        { t: "13:06:31", who: "Диспетчер", text: "Задымление на кухне" },
        { t: "13:08:44", who: "Иванов А. С.", text: "Обработка приостановлена на шаге 3" },
      ],
    },
    {
      id: "INC-1833",
      time: "12:58:17",
      typeId: "loiter",
      type: "Скопление людей",
      site: "Складской комплекс",
      siteType: "Склад",
      location: "Этаж А, разгрузочная рампа",
      region: "Складской комплекс",
      priority: "low",
      status: "new",
      operator: null,
      slaSec: 720,
      deviceIds: ["device-11", "device-10"],
      media: "video",
      cameras: ["device-11", "device-10"],
      answers: {},
      launched: [],
      log: [{ t: "12:58:17", who: "Видеоаналитика", text: "Группа людей у рампы дольше 10 минут" }],
    },
    {
      id: "INC-1832",
      time: "12:49:53",
      typeId: "intrusion",
      type: "Проникновение",
      site: "Главный офис",
      siteType: "Офис",
      location: "2-й этаж, отдел разработки",
      region: "Главный офис",
      priority: "medium",
      status: "foreign",
      operator: "Петрова М.",
      slaSec: 600,
      deviceIds: ["device-5"],
      media: "video",
      cameras: ["device-5"],
      answers: { visual: true },
      launched: [],
      log: [
        { t: "12:49:53", who: "СКУД", text: "Проход без карты в нерабочее время" },
        { t: "12:51:02", who: "Петрова М.", text: "Взято в работу · шаг 1/5" },
      ],
    },
    {
      id: "INC-1831",
      time: "12:41:26",
      typeId: "fire",
      type: "Пожарная тревога",
      site: "Технопарк",
      siteType: "Лаборатория",
      location: "Корпус А, лаборатория 1",
      region: "Технопарк",
      priority: "high",
      status: "closed",
      operator: "Сидоров К.",
      slaSec: 0,
      deviceIds: ["fire-4", "device-15", "device-16"],
      media: "map",
      cameras: ["device-15"],
      answers: { visual: true, verdict: "Ложная", kind: "Тест системы", note: "Плановая проверка АПС" },
      closeResult: "drill",
      launched: [],
      log: [
        { t: "12:41:26", who: "Диспетчер", text: "Сработка пожарного датчика" },
        { t: "12:47:10", who: "Сидоров К.", text: "Инцидент закрыт: плановый тест" },
      ],
    },
    {
      id: "INC-1830",
      time: "12:33:04",
      typeId: "sabotage",
      type: "Саботаж камеры",
      site: "Торговый центр",
      siteType: "Торговый центр",
      location: "1-й этаж, витрина у входа",
      region: "Торговый центр",
      priority: "medium",
      status: "new",
      operator: null,
      slaSec: 420,
      deviceIds: ["device-26"],
      media: "video",
      cameras: ["device-26"],
      answers: {},
      launched: [],
      log: [{ t: "12:33:04", who: "Видеоаналитика", text: "Камера смещена с сектора обзора" }],
    },
    {
      id: "INC-1829",
      time: "12:25:40",
      typeId: "intrusion",
      type: "Проникновение",
      site: "Технопарк",
      siteType: "Офис",
      location: "Корпус Б, коридор",
      region: "Технопарк",
      priority: "low",
      status: "closed",
      operator: "Иванов А. С.",
      slaSec: 0,
      deviceIds: ["device-20"],
      media: "video",
      cameras: ["device-20"],
      answers: { visual: true, verdict: "Персонал / ложная", note: "Сотрудник клининга по графику" },
      launched: [],
      log: [
        { t: "12:25:40", who: "СКУД", text: "Открытие двери без карты" },
        { t: "12:28:55", who: "Иванов А. С.", text: "Инцидент закрыт" },
      ],
    },
    {
      id: "INC-1828",
      time: "12:17:12",
      typeId: "fire",
      type: "Пожарная тревога",
      site: "Главный офис",
      siteType: "Офис",
      location: "Приемная, зона ожидания",
      region: "Главный офис",
      priority: "high",
      status: "new",
      operator: null,
      slaSec: 330,
      deviceIds: ["fire-6", "device-31"],
      media: "both",
      cameras: ["device-31"],
      answers: {},
      launched: [],
      log: [{ t: "12:17:12", who: "Диспетчер", text: "Сработка датчика дыма в зоне ожидания" }],
    },
    {
      id: "INC-1827",
      time: "12:08:35",
      typeId: "loiter",
      type: "Скопление людей",
      site: "Торговый центр",
      siteType: "Торговый центр",
      location: "1-й этаж, кассовая зона",
      region: "Торговый центр",
      priority: "low",
      status: "new",
      operator: null,
      slaSec: 780,
      deviceIds: ["device-24"],
      media: "video",
      cameras: ["device-24"],
      answers: {},
      launched: [],
      log: [{ t: "12:08:35", who: "Видеоаналитика", text: "Очередь на кассах дольше норматива" }],
    },
    {
      id: "INC-1826",
      time: "11:59:48",
      typeId: "intrusion",
      type: "Проникновение",
      site: "Складской комплекс",
      siteType: "Склад",
      location: "Склад №1, стеллажи А1–А8",
      region: "Складской комплекс",
      priority: "medium",
      status: "closed",
      operator: "Петрова М.",
      slaSec: 0,
      deviceIds: ["device-9", "device-8"],
      media: "video",
      cameras: ["device-8"],
      answers: { visual: true, verdict: "Персонал / ложная", zone: "Склад" },
      launched: [],
      log: [
        { t: "11:59:48", who: "Видеоаналитика", text: "Движение в закрытой зоне" },
        { t: "12:04:19", who: "Петрова М.", text: "Инцидент закрыт" },
      ],
    },
  ];

  // Адресаты эскалации: в продукте — пользователи и роли из системы прав доступа.

  /* ===== Операторы и дежурные группы (§8.1) ===== */

  const OPERATORS = [
    { id: "me", name: ME, role: "оператор", duty: "на смене", self: true },
    { id: "petrova", name: "Петрова М.", role: "старший смены", duty: "на смене" },
    { id: "sidorov", name: "Сидоров К.", role: "оператор", duty: "на смене" },
    { id: "noc", name: "Дежурный ЦОД", role: "круглосуточный пост", duty: "на смене" },
    { id: "gusev", name: "Гусев Р. А.", role: "начальник охраны площадки", duty: "на смене" },
    { id: "kuznetsov", name: "Кузнецов И. П.", role: "инженер ТСО", duty: "по вызову" },
  ];

  // Инцидент можно адресовать дежурной группе: владельцем становится человек,
  // который первым нажал «Принять».
  const GROUPS = [
    {
      id: "grp-leads",
      name: "Дежурная группа старших",
      role: "группа",
      duty: "на смене",
      group: true,
      members: ["petrova", "me"],
    },
  ];

  const ACTORS = OPERATORS.concat(GROUPS, [
    { id: "dispatcher", name: "Диспетчер", role: "система", system: true },
    { id: "system", name: "Система", role: "система", system: true },
  ]);

  const SIM = {
    enabled: true,
    colleagues: ["sidorov", "petrova", "gusev"],
    firstTakeSec: 12,
    takeEverySec: 24,
    stepEverySec: 11,
    handoffSec: 46,
    dropSec: 88,
    maxTaken: 3,
    taken: 0,
    takeTick: 0,
    stepTick: 0,
    handoffTick: 0,
    dropTick: 0,
    handoffDone: false,
    dropDone: false,
  };

  const SIM_NOTES = [
    "Охрана направлена, время прибытия 2 мин",
    "Передано бригадиру, акт №14-СБ",
    "Уточняю по архиву, свидетелей нет",
    "Наряд на месте, инцидент локализован",
  ];

  window.IM_DEMO = {
    ME,
    SCENARIOS,
    DEVICE_TYPES,
    DEVICE_CATALOG,
    DEVICES_IN_REPAIR,
    PAGE_SIZE,
    TREE,
    EVENTS,
    OPERATORS,
    GROUPS,
    ACTORS,
    SIM,
    SIM_NOTES,
  };
})();
